-- zemoga_test_db.portfolio definition
CREATE DATABASE `zemoga_test_db` /*!40100 DEFAULT CHARACTER SET latin1 */;


CREATE TABLE `zemoga_test_db.portfolio` (
  `idportfolio` int(11) NOT NULL AUTO_INCREMENT,
  `description` varchar(255) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `twitter_user_name` varchar(255) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `user_id` varchar(255) NOT NULL,
  `experience_summary` varchar(255) DEFAULT NULL,
  `last_names` varchar(255) DEFAULT NULL,
  `names` varchar(255) DEFAULT NULL,
  `twitter_user_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`idportfolio`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO zemoga_test_db.portfolio (idportfolio,description,image_url,twitter_user_name,title,user_id,experience_summary,last_names,names,twitter_user_id) VALUES
	 (1,'Tyrion of House Lannister. Imp, Halfman. Never forget what you are, for surely the world will not. Not affiliated with #GameofThrones or HBO ++++--2','https://pbs.twimg.com/profile_images/668279339838935040/8sUE9d4C_400x400.jpg','GoT_Tyrion','Tyrion Lannister2','',NULL,NULL,NULL,NULL),
	 (2,'Daenerys is one of the last surviving members (along with her older brother, Viserys) of House Targaryen which, until 14 years before the events of the first novel','https://pbs.twimg.com/profile_images/1117967801652617216/i8PWXebo_400x400.jpg','Daenerys','Daenerys Targaryen','',NULL,NULL,NULL,NULL),
	 (3,'Stephen William Hawking CH CBE FRS FRSA was an English theoretical physicist, cosmologist','https://www.biografiasyvidas.com/biografia/h/fotos/hawking_stephen_1.jpg','Stephen','Scientist','',NULL,NULL,NULL,NULL),
	 (4,'Sansa like true knights, songs and dogs. I hate babysitting. Currently being polite and trying not to die','https://pbs.twimg.com/profile_images/1812114126/newtwitter_400x400.jpg','Lady_Sansa','Sansa Stark','',NULL,NULL,NULL,NULL),
	 (5,'HBO Game of Thrones series 2','https://pbs.twimg.com/profile_images/1108745277941387264/SYLsEwkd_400x400.png','GameOfThrones','Game of Thrones','',NULL,NULL,NULL,NULL),
	 (6,'Error description','Error image','Error_user_xxx157','Error User XXX 157','',NULL,NULL,NULL,NULL),
	 (7,'Actress, I love have a nice life, I''m crazy and no perfect, Single(Parody/RP)','https://upload.wikimedia.org/wikipedia/commons/5/57/Scarlett_Johansson_by_Gage_Skidmore_2_%28cropped%29_%28cropped%29.jpg','ScarletJohanso','Scarlet Johanson','',NULL,NULL,NULL,NULL),
	 (8,'President-elect, husband to @DrBiden, proud father & grandfather. Ready to build back better for all Americans.','https://pbs.twimg.com/profile_images/1308769664240160770/AfgzWVE7_400x400.jpg','JoeBiden','Joe Biden','',NULL,NULL,NULL,NULL),
	 (9,'Ex jugador de fútbol colombiano. Mundial 90 - 94 - 98 #TodoBien. Contacto pibevalderramap10@gmail.com.','https://pbs.twimg.com/profile_images/796791973516640256/66rBJ4Ie_400x400.jpg','PibeValderramaP','Carlos Valderrama','',NULL,NULL,NULL,NULL),
	 (10,'Adele Laurie Blue Adkins (Londres, 5 de mayo de 1988), conocida simplemente como Adele, es una cantante, compositora y multinstrumentista británica.3? Desde muy joven mostró su interés por la música y en 2006 egresó de la BRIT School de Artes Escénicas y ','https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Adele_2016.jpg/1280px-Adele_2016.jpg','Adele','Adele','',NULL,NULL,NULL,NULL);
INSERT INTO zemoga_test_db.portfolio (idportfolio,description,image_url,twitter_user_name,title,user_id,experience_summary,last_names,names,twitter_user_id) VALUES
	 (11,'Nicolás Maduro Moros (Caracas; 23 de noviembre de 1962) es un político, diplomático y dirigente sindical venezolano que ha ejercido como ministro de relaciones exteriores entre 2006 y 2012, como vicepresidente de la república desde 2012 al 2013 y presiden','https://upload.wikimedia.org/wikipedia/commons/f/f9/Nicol%C3%A1s_Maduro_%282019-10-25%29_02.jpg','NicolasMaduro','Nicolás Maduro','',NULL,NULL,NULL,NULL),
	 (12,'Edward Christopher Sheeran (/???æn/; Halifax, Inglaterra; 17 de febrero de 1991), más conocido como Ed Sheeran, es un cantautor y músico británico.2? A corta edad, comenzó a cantar en la iglesia a la que asistía y también aprendió a tocar la guitarra. A l','https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Ed_Sheeran-6826_%28cropped%29.jpg/1280px-Ed_Sheeran-6826_%28cropped%29.jpg','Edd_sheerannn','?ultiply','',NULL,NULL,NULL,NULL),
	 (13,'Cristiano Ronaldo dos Santos Aveiro, GOIH, ComM8?9?10? (pronunciación en portugués: /k?i??ti?nu ?u?na?du/) (Funchal, Madeira; 5 de febrero de 1985), más conocido como Cristiano Ronaldo, es un futbolista portugués que juega como delantero en la Juventus F.','https://upload.wikimedia.org/wikipedia/commons/8/8c/Cristiano_Ronaldo_2018.jpg','Cristiano','Cristiano Ronaldo','',NULL,NULL,NULL,NULL),
	 (14,'Shakira Isabel Mebarak Ripoll (Barranquilla; 2 de febrero de 1977), conocida artísticamente como Shakira, es una cantautora, productora discográfica, actriz, bailarina, empresaria, embajadora de buena voluntad de UNICEF y filántropa colombiana. Su alto ni','https://upload.wikimedia.org/wikipedia/commons/d/de/Shakira2009.jpg','shakira','shakira','',NULL,NULL,NULL,NULL),
	 (15,'Greta Tintin Eleonora Ernman Thunberg (Estocolmo, 3 de enero de 2003), más conocida como Greta Thunberg,nota 1? es una activista medioambiental sueca, centrada en los riesgos planteados por el calentamiento global. ','https://upload.wikimedia.org/wikipedia/commons/4/47/Greta_Thunberg_urges_MEPs_to_show_climate_leadership_%2849618310531%29_%28cropped%29.jpg','GretaThunberg','Greta Thunberg','',NULL,NULL,NULL,NULL),
	 (16,'James David Rodríguez Rubio (Cúcuta, Norte de Santander, Colombia, 12 de julio de 1991) es un futbolista colombiano nacionalizado español.1? Juega como centrocampista y su equipo actual es el Everton Football Club de la Premier League de Inglaterra. Ademá','https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/James_Rodriguez_Training_2019-04-10_FC_Bayern_Muenchen-1.jpg/1280px-James_Rodriguez_Training_2019-04-10_FC_Bayern_Muenchen-1.jpg','jamesdrodriguez','James Rodríguez','',NULL,NULL,NULL,NULL),
	 (17,'Taylor Alison Swift (Reading, Pensilvania; 13 de diciembre de 1989) es una cantante, compositora, productora, filántropa y actriz estadounidense. Criada en Wyomissing (Pensilvania), se mudó a Nashville (Tennessee) a los 14 años para realizar una carrera d','https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Taylor_Swift_2_-_2019_by_Glenn_Francis_%28cropped%29_3.jpg/1280px-Taylor_Swift_2_-_2019_by_Glenn_Francis_%28cropped%29_3.jpg','Tailor_Swift','Tailor Swift','',NULL,NULL,NULL,NULL),
	 (18,'William Henry Gates III (Seattle, Washington; 28 de octubre de 1955), mejor conocido como Bill Gates, es un empresario, informático y filántropo estadounidense, conocido por haber creado y fundado junto con Paul Allen, la empresa Microsoft. De igual forma','https://upload.wikimedia.org/wikipedia/commons/5/5c/Bill_Gates_June_2015.png','BillGates','Bill Gates','',NULL,NULL,NULL,NULL),
	 (19,'The World Health Organization (WHO) is a specialized agency of the United Nations responsible for international public health.[1] The WHO Constitution, which establishes the agencys governing structure and principles, states its main objective as "the att','https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Emblem_of_the_United_Nations.svg/1920px-Emblem_of_the_United_Nations.svg.png','WHO','World Health Organization (WHO)','',NULL,NULL,NULL,NULL),
	 (20,'Iván Duque Márquez (Spanish pronunciation: [i??an ?du.ke ?ma?kes]; born 1 August 1976) is a Colombian politician and lawyer who is the current president of Colombia, in office since 7 August 2018. He was elected Colombias youngest president, as the candid','https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Secretary_Pompeo_Delivers_a_Press_Statement_with_Colombian_President_Duque_%2850369491081%29_%28cropped%29.jpg/1280px-Secretary_Pompeo_Delivers_a_Press_Statement_with_Colombian_President_Duque_%285','IvanDuque','Iván Duque','',NULL,NULL,NULL,NULL);
INSERT INTO zemoga_test_db.portfolio (idportfolio,description,image_url,twitter_user_name,title,user_id,experience_summary,last_names,names,twitter_user_id) VALUES
	 (21,'Barack Hussein Obama II (/b??r??k hu??se?n o??b??m?/ (About this soundlisten) b?-RAHK hoo-SAYN oh-BAH-m?;[1] born August 4, 1961) is an American politician and attorney who served as the 44th president of the United States from 2009 to 2017. A member of t','https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/1280px-President_Barack_Obama.jpg','BarackObama','Barack Obama','',NULL,NULL,NULL,NULL),
	 (22,'orge Iván Ospina (born October 1965 in Cali, Colombia) is former Colombian Senator and current mayor of Santiago de Cali, the third largest city in Colombia and the economic hub for Southwestern Colombia.[1] Ospina is also a doctor who has worked in the h','https://upload.wikimedia.org/wikipedia/commons/5/59/Jorge_perfil.jpg','JorgeIvanOspina','Jorge Ivan Ospina','',NULL,NULL,NULL,NULL),
	 (23,'Nairo Alexander Quintana Rojas, ODB, (born 4 February 1990) is a Colombian racing cyclist, who currently rides for UCI ProTeam Arkéa–Samsic.[6] Nicknamed "Nairoman" and "El Cóndor de los Andes", Quintana is a specialist climber','https://e00-marca.uecdn.es/assets/multimedia/imagenes/2020/03/25/15851383990988.jpg','NairoQuinCo','Nairo Quintana','',NULL,NULL,NULL,NULL),
	 (24,'Angela Dorothea Merkel[a] (née Kasner; born 17 July 1954) is a German politician who has been Chancellor of Germany since 2005. She served as Leader of the Opposition from 2002 to 2005 and as Leader of the Christian Democratic Union (CDU) from 2000 to 201','https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Angela_Merkel_2019_cropped.jpg/1280px-Angela_Merkel_2019_cropped.jpg','AngelaM_queen','Angela Merkel','',NULL,NULL,NULL,NULL),
	 (25,'Leonardo Wilhelm DiCaprio (/d??kæprio?/, Italian: [di?ka?prjo]; born November 11, 1974) is an American actor, film producer and environmentalist. He has often played unconventional roles, particularly in biopics and period films. As of 2019, his films hav','https://upload.wikimedia.org/wikipedia/commons/4/46/Leonardo_Dicaprio_Cannes_2019.jpg','LeoDiCaprio','Leonardo DiCaprio','',NULL,NULL,NULL,NULL),
	 (26,'Angelina Jolie (/d?o??li?/; née Voight, formerly Jolie Pitt,[4] born June 4, 1975)[5] is an American actress, filmmaker, and humanitarian. The recipient of numerous accolades, including an Academy Award and three Golden Globe Awards, she has been named Ho','https://upload.wikimedia.org/wikipedia/commons/a/ad/Angelina_Jolie_2_June_2014_%28cropped%29.jpg','angelinajolie03','Angelina Jolie Fans','',NULL,NULL,NULL,NULL),
	 (987654321,'Tyrion of House Lannister. Imp, Halfman. Never forget what you are, for surely the world will not. Not affiliated with #GameofThrones or HBO2','https://pbs.twimg.com/profile_images/668279339838935040/8sUE9d4C_400x400.jpg','GoT_Tyrion','updatePortfolioModifyThePortfolio2','',NULL,NULL,NULL,NULL),
	 (987654322,'Is an American stand-up comedian, actor, and producer. Born and raised in Philadelphia, Pennsylvania, Hart began his career by winning several amateur comedy competitions at clubs throughout New England','https://variety.com/wp-content/uploads/2017/05/kevin-hart-variety-cover-story-2.jpg?w=681&h=383&crop=1','KevinHart4real','Kevin Hart','',NULL,NULL,NULL,NULL);
